Add `instance Display Void`
haskell-text/text-display pull request #28
Opened 2022-11-14 16:04 UTC by MangoIV

## Submitter checklist

I have updated the instances to also contain an instance for `Void`, I have not included a note in the `CHANGELOG.md` because I think that it's much more a fix of a missing instance than a feature addition. If you like me to also add it to the `CHANGELOG`, just tell me.

- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/Kleidukos/text-display/blob/main/CONTRIBUTING.md)

2022-11-14 16:40 UTC, Kleidukos requested changes
Hi, and thank you for this contribution!

2 things:

1. It seems that your editor has taken upon itself to reformat the codebase. We abide by the CI and Fourmolu to do that. Especially, the `ImportQualifiedPost` extension is not supported by some of the versions of GHC tested in CI.

2. Yes I'd very much prefer that you include it in the changelog :)

2022-11-14 17:10 UTC, MangoIV commented
I formatted it according to the `fourmolu.yaml` (see the second commit)
I'll add the addition to the `CHANGELOG.md`

2022-11-14 18:18 UTC, MangoIV commented
Ah I know why that happened; I have a big fourmolu command I run over all my files and that has -XImpirtQualifiedPost; however, the formatting seems not to be up to date on main, anyhow.

2022-11-14 21:49 UTC, MangoIV commented
sorry for the fuzz.

2022-11-15 08:52 UTC, Kleidukos commented
@MangoIV could you please rebase your PR on `main`? :)

2022-11-15 11:26 UTC, MangoIV commented
done :+1:

2022-11-16 00:16 UTC, Kleidukos approved these changes
Fantastic! Thank you very much for this addition :)

2022-11-16 00:16 UTC, merged